# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
  sylius_cart_restaurant_session_key_name: _coopcycle.sylius.cart.restaurant

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  app.locale_listener:
    class: AppBundle\EventListener\LocaleListener
    arguments: ['%kernel.default_locale%']
    tags:
      - { name: kernel.event_subscriber }

  sylius.context.locale.request_based:
    class: Sylius\Bundle\LocaleBundle\Context\RequestBasedLocaleContext
    arguments: ['@request_stack', '@sylius.locale_provider']
    tags:
      - { name: sylius.context.locale, priority: 128 }

  sylius.context.locale.immutable:
    class: Sylius\Component\Locale\Context\ImmutableLocaleContext
    arguments: ['%sylius_locale.locale%']
    tags:
      - { name: sylius.context.locale, priority: 64 }

  sylius.order_processing.order_taxes_processor:
    class: AppBundle\Sylius\OrderProcessing\OrderTaxesProcessor
    arguments:
      - "@sylius.factory.adjustment"
      - "@sylius.tax_rate_resolver"
      - "@sylius.tax_calculator"
    tags:
      - { name: sylius.order_processor, priority: 32 }

  sylius.order_processing.order_payment_processor:
    class: AppBundle\Sylius\OrderProcessing\OrderPaymentProcessor
    arguments:
      - "@doctrine"
    tags:
      - { name: sylius.order_processor, priority: 16 }

  coopcycle.sylius.factory.product_variant:
    class: AppBundle\Sylius\Product\ProductVariantFactory
    decorates: sylius.factory.product_variant
    arguments:
      - "@coopcycle.sylius.factory.product_variant.inner"
      - "@sylius.repository.product"
      - "@sylius.repository.product_variant"
      - "@sylius.repository.tax_category"
      - "@sylius.repository.product_option"
      - "@sylius.factory.product_option"
      - "@sylius.factory.product_option_value"
      - "@coopcycle.settings_manager"
      - "@translator"
    public: false

  coopcycle.sylius.factory.product:
    class: AppBundle\Sylius\Product\ProductFactory
    decorates: sylius.factory.product
    arguments:
      - "@coopcycle.sylius.factory.product.inner"
      - "@slugify"
    public: false

  coopcycle.sylius.factory.order:
    class: AppBundle\Sylius\Order\OrderFactory
    decorates: sylius.factory.order
    arguments:
      - "@coopcycle.sylius.factory.order.inner"
      - "@sylius.factory.adjustment"
    public: false

  sylius.context.cart.restaurant:
    class: AppBundle\Sylius\Cart\RestaurantCartContext
    arguments:
      - "@session"
      - "@sylius.repository.order"
      - "@sylius.factory.order"
      - "@coopcycle.repository.restaurant"
      - "%sylius_cart_restaurant_session_key_name%"
    tags:
      - { name: sylius.context.cart, priority: 32 }

  app.form.api_registration:
    class: AppBundle\Form\ApiRegistrationType
    arguments: ['%country_iso%']
    tags:
      - { name: form.type, alias: app_user_api_registration }

  app.form.registration:
    class: AppBundle\Form\RegistrationType
    arguments: ['%country_iso%', '%is_demo%']
    tags:
      - { name: form.type }

  app.form.update_profile:
    class: AppBundle\Form\UpdateProfileType
    arguments: [ '@security.token_storage', '@translator', '%country_iso%' ]
    tags:
      - { name: form.type, alias: app_update_profile }

  coopcycle.repository.zone:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\Zone

  coopcycle.expression_language.zone.provider:
    public: false
    class: AppBundle\ExpressionLanguage\ZoneExpressionLanguageProvider
    arguments: [ '@coopcycle.repository.zone' ]

  coopcycle.expression_language:
    public: true
    class: AppBundle\ExpressionLanguage\ExpressionLanguage
    arguments:
      - null
      - [ "@coopcycle.expression_language.zone.provider" ]

  my.registration_listener:
    class: AppBundle\EventListener\RegistrationListener
    arguments: ['@router']
    tags:
      - { name: kernel.event_subscriber }

  'AppBundle\EventListener\SyliusIdGeneratorSubscriber':
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  'AppBundle\EventListener\TaggableSubscriber':
    arguments: [ '@coopcycle.tag_manager' ]
    tags:
      - { name: doctrine.event_subscriber, connection: default }

  coopcycle.tag_manager:
    class: AppBundle\Service\TagManager
    arguments: [ '@doctrine' ]

  coopcycle.tax_calculator.float:
    class: AppBundle\Service\Taxation\FloatCalculator
    tags:
      - { name: sylius.tax_calculator, calculator: float, label: "Float" }

  coopcycle.order_manager:
    public: true
    class: AppBundle\Service\OrderManager
    arguments:
      - "@doctrine"
      - "@routing_service"
      - "@sm.factory"
      - "@coopcycle.settings_manager"
      - "@event_dispatcher"

  coopcycle.delivery.manager:
    class: AppBundle\Service\DeliveryManager
    arguments:
      - "@coopcycle.expression_language"

  coopcycle.cart_provider:
    class: AppBundle\Service\CartProviderService
    arguments:
      - "@sylius.context.cart"
      - "@serializer"

  delivery.entity_listener:
    class: AppBundle\Entity\Listener\DeliveryListener
    arguments: [ '@event_dispatcher' ]
    tags:
      - { name: doctrine.orm.entity_listener }

  task.entity_listener:
    class: AppBundle\Entity\Listener\TaskListener
    arguments: [ "@event_dispatcher", "@logger" ]
    tags:
      - { name: doctrine.orm.entity_listener }

  menu_item.entity_listener:
    class: AppBundle\Entity\Listener\MenuItemListener
    arguments:
      - "@sylius.factory.product"
      - "@sylius.factory.product_variant"
      - "@sylius.repository.product"
      - "@sylius.repository.product_variant"
    tags:
      - { name: doctrine.orm.entity_listener }

  my.delivery_normalizer:
    class: AppBundle\Serializer\DeliveryNormalizer
    arguments: [ "@api_platform.jsonld.normalizer.item" ]
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  app.menu_normalizer:
    class: AppBundle\Serializer\MenuNormalizer
    arguments:
      - "@api_platform.jsonld.normalizer.item"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  app.restaurant_normalizer:
    class: AppBundle\Serializer\RestaurantNormalizer
    arguments:
      - "@api_platform.jsonld.normalizer.item"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  coopcycle.api.normalizer.task:
    class: AppBundle\Serializer\TaskNormalizer
    arguments:
      - "@api_platform.jsonld.normalizer.item"
      - "@api_platform.iri_converter"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  coopcycle.api.normalizer.task_list:
    class: AppBundle\Serializer\TaskListNormalizer
    arguments:
      - "@api_platform.jsonld.normalizer.item"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  app.menu_section:
    class: AppBundle\Serializer\MenuSectionNormalizer
    arguments:
      - "@api_platform.jsonld.normalizer.item"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  app.menu_item_normalizer:
    class: AppBundle\Serializer\MenuItemNormalizer
    arguments:
      - "@api_platform.jsonld.normalizer.item"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  coopcycle.normalizer.cart:
    class: AppBundle\Serializer\CartNormalizer
    arguments:
      - "@serializer.normalizer.object"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  coopcycle.normalizer.order.jsonld:
    class: AppBundle\Serializer\JsonLd\OrderNormalizer
    arguments:
      - "@api_platform.jsonld.normalizer.item"
      - "@api_platform.iri_converter"
      - "@coopcycle.sylius.factory.order"
      - "@sylius.repository.product_variant"
      - "@sylius.factory.order_item"
      - "@sylius.factory.adjustment"
      - "@sylius.order_item_quantity_modifier"
      - "@sylius.order_modifier"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  coopcycle.normalizer.order_item.json:
    class: AppBundle\Serializer\Json\OrderItemNormalizer
    arguments:
      - "@serializer.normalizer.object"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  coopcycle.normalizer.notification.json:
    class: AppBundle\Serializer\Json\NotificationNormalizer
    arguments:
      - "@serializer.normalizer.object"
      - "@router"
      - "@translator"
    tags: [ { name: serializer.normalizer, priority: 128 } ]

  'AppBundle\Form\DeliveryType':
    arguments: [ '@doctrine', '@routing_service', '@translator' ]
    tags:
      - { name: form.type }

  'AppBundle\Form\DeliveryEmbedType':
    arguments: [ '@doctrine', '@routing_service', '@translator', '%country_iso%' ]
    tags: [ form.type ]

  'AppBundle\Form\MenuType\MenuItemModifierType':
    arguments: [ '@translator' ]
    tags: [ form.type ]

  'AppBundle\Form\OrderType':
    arguments: [ '@sm.factory', '@security.authorization_checker' ]
    tags: [ form.type ]

  'AppBundle\Form\TaskUploadType':
    arguments: [ '@craue_config', '@csa_guzzle.client.google_maps', '@translator', '@coopcycle.tag_manager' ]
    tags: [ form.type ]

  'AppBundle\Form\TaskExportType':
    arguments: [ '@coopcycle.repository.task' ]
    tags: [ form.type ]

  'AppBundle\Form\SettingsType':
    arguments: [ '@coopcycle.settings_manager' ]
    tags: [ form.type ]

  'AppBundle\Form\TaskType':
    arguments: [ '@coopcycle.tag_manager' ]
    tags: [ form.type ]

  'AppBundle\Form\RestaurantType':
    arguments: [ '@security.authorization_checker', '@security.token_storage' ]
    tags: [ form.type ]

  'AppBundle\Form\StoreType':
    arguments: [ '@security.authorization_checker', '@security.token_storage' ]
    tags: [ form.type ]

  my.jwt_listener:
    class: AppBundle\EventListener\JwtListener
    tags:
      - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

  my.delivery_repository:
    class: AppBundle\Entity\DeliveryRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\Delivery

  coopcycle.repository.task:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\Task

  coopcycle.repository.restaurant:
    class: AppBundle\Entity\RestaurantRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\Restaurant

  routing_service:
    public: true
    class: AppBundle\Service\Routing\Osrm
    arguments:
      - '@csa_guzzle.client.osrm'

  'AppBundle\Filter\RestaurantFilter':
    arguments: [ '@doctrine', '@request_stack', '@logger', { distance: "exact", coordinate: "exact" } ]
    tags: [ 'api_platform.filter' ]

  twig.extension.text:
    class: Twig_Extensions_Extension_Text
    tags:
      - { name: twig.extension }

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

  coopcycle.twig.runtime.order_state_resolver:
    class: AppBundle\Twig\OrderStateResolver
    arguments: [ '@sm.factory' ]
    public: false
    tags:
      - { name: twig.runtime }

  swiftmailer.transport.eventdispatcher.mailjet:
    class: Swift_Events_SimpleEventDispatcher

  swiftmailer.mailer.transport.mailjet:
      class: AppBundle\Service\MailjetTransport
      arguments:
          - "@swiftmailer.transport.eventdispatcher.mailjet"
          - "%mailjet.api_key%"
          - "%mailjet.secret_key%"
          - "@logger"

  swiftmailer.logger:
      class: AppBundle\Service\MailLoggerService
      arguments: ["@logger"]
      tags:
        - { name: monolog.logger, channel: mailer }
        - { name: "swiftmailer.default.plugin" }

  coopcycle.metrics_helper:
    class: AppBundle\Utils\MetricsHelper
    arguments:
      - "%database_name%"
      - "@m6_statsd"

  coopcycle.web_success_handler:
    class: AppBundle\EventListener\AuthenticationWebSuccessHandler
    arguments: ['@router']

  coopcycle.task_manager:
    class: AppBundle\Service\TaskManager
    arguments: ["@doctrine", "@event_dispatcher"]

  coopcycle.settings_manager:
    class: AppBundle\Service\SettingsManager
    arguments: ["@craue_config", "%craue_config.entity_name%", "@doctrine", "@logger"]

  coopcycle.email_manager:
    class: AppBundle\Service\EmailManager
    arguments:
      - "@mailer"
      - "@templating"
      - "@translator"
      - "@coopcycle.settings_manager"
      - "%transactional_address%"

  coopcycle.notification_manager:
    class: AppBundle\Service\NotificationManager
    arguments:
      - "@doctrine"
      - "@snc_redis.default"
      - "@serializer"
      - "@translator"

  coopcycle.remote_push_notification_manager:
    class: AppBundle\Service\RemotePushNotificationManager
    arguments:
      - "@csa_guzzle.client.fcm"
      - "@apns_php.push"
      - "%apns_certificate_pass_phrase%"
      - "%fcm_server_api_key%"

  'AppBundle\Validator\Constraints\CartValidator':
    arguments: [ '@routing_service' ]
    tags:
      - { name: validator.constraint_validator }

  'AppBundle\Validator\Constraints\DeliveryValidator':
    arguments: [ '@routing_service' ]
    tags:
      - { name: validator.constraint_validator }

  'AppBundle\Validator\Constraints\OrderValidator':
    arguments: [ '@routing_service' ]
    tags:
      - { name: validator.constraint_validator }

  # Order of Doctrine Subscribers is important !
  # - DeliverySubscriber
  # - TaskCollectionSubscriber

  'AppBundle\EventListener\DeliverySubscriber':
    tags:
      - { name: doctrine.event_subscriber, connection: default, priority: 256 }

  'AppBundle\EventListener\TaskCollectionSubscriber':
    arguments: [ '@event_dispatcher', '@routing_service', '@logger' ]
    tags:
      - { name: doctrine.event_subscriber, connection: default, priority: 128 }

  'AppBundle\Api\EventSubscriber\RemotePushTokenSubscriber':
      arguments:
          - '@security.token_storage'
          - '@doctrine'
          - '@logger'
      tags: [ 'kernel.event_subscriber' ]
