winzou_state_machine:
    sylius_order:
        class: "%sylius.model.order.class%"
        property_path: state
        graph: sylius_order
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            cancelled: ~
            fulfilled: ~
            accepted: ~
            refused: ~
            ready: ~
        transitions:
            create:
                from: [cart]
                to: new
            cancel:
                from: [new, accepted]
                to: cancelled
            fulfill:
                from: [accepted, ready]
                to: fulfilled
            accept:
                from: [new]
                to: accepted
            refuse:
                from: [new]
                to: refused
            ready:
                from: [accepted]
                to: ready
        callbacks:
            before:
                before_create_assign_number:
                    on: "create"
                    do: ["@sylius.order_number_assigner", "assignNumber"]
                    args: ["object"]
                before_fulfill_capture_payment:
                    on: "fulfill"
                    do: ["@coopcycle.order_manager", "capturePayment"]
                    args: ["object"]
            after:
                after_create_dispatch_event:
                    on: "create"
                    do: ["@coopcycle.order_manager", "dispatchOrderEvent"]
                    args: ["object", "'order.create'"]
                after_accept_create_delivery:
                    on: "accept"
                    do: ["@coopcycle.order_manager", "createDelivery"]
                    args: ["object"]
                after_accept_dispatch_event:
                    on: "accept"
                    do: ["@coopcycle.order_manager", "dispatchOrderEvent"]
                    args: ["object", "'order.accept'"]
                after_refuse_send_email:
                    on: "refuse"
                    do: ["@coopcycle.order_manager", "dispatchOrderEvent"]
                    args: ["object", "'order.cancel'"]
                after_cancel_send_email:
                    on: "cancel"
                    do: ["@coopcycle.order_manager", "dispatchOrderEvent"]
                    args: ["object", "'order.cancel'"]
    sylius_payment:
        class: AppBundle\Entity\StripePayment
        property_path: state
        graph: sylius_payment
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            new: ~
            authorized: ~
            processing: ~
            completed: ~
            failed: ~
            cancelled: ~
            void: ~
            refunded: ~
        transitions:
            create:
                from: [cart]
                to: new
            authorize:
                from: [new, cart]
                to: authorized
            process:
                from: [new]
                to: processing
            complete:
                from: [new, authorized, processing]
                to: completed
            fail:
                from: [new, authorized]
                to: failed
            cancel:
                from: [new]
                to: cancelled
            refund:
                from: [completed]
                to: refunded
            void:
                from: [new, processing]
                to: void
        callbacks:
            after:
                after_create_authorize_payment:
                    on: "create"
                    do: ["@coopcycle.order_manager", "authorizePayment"]
                    args: ["object.getOrder()"]
                after_authorize_dispatch_event:
                    on: "authorize"
                    do: ["@coopcycle.order_manager", "dispatchPaymentEvent"]
                    args: ["object", "'payment.authorize'"]
                after_complete_create_transfer:
                    on: "complete"
                    do: ["@coopcycle.order_manager", "createTransfer"]
                    args: ["object"]
                after_fail_transfer:
                    on: "fail"
                    do: ["@coopcycle.order_manager", "afterPaymentFailed"]
                    args: ["object.getOrder()"]
    stripe_transfer:
        class: AppBundle\Entity\StripeTransfer
        property_path: state
        graph: stripe_transfer
        state_machine_class: "%sylius.state_machine.class%"
        states:
            new: ~
            completed: ~
            failed: ~
            refunded: ~
        transitions:
            complete:
                from: [new]
                to: completed
            fail:
                from: [new]
                to: failed
            refund:
                from: [completed]
                to: refunded
