profile_order_invoice:
    path:     /profile/orders/CPCCL-{number}.pdf
    defaults: { _controller: AppBundle:Profile:orderInvoice }
    methods:  [ GET ]

profile_order:
    path:     /profile/orders/{id}
    defaults: { _controller: AppBundle:Profile:order }
    methods:  [ GET, POST ]

profile_orders:
    path:     /profile/orders
    defaults:
        _controller: AppBundle:Profile:orderList
        layout: AppBundle::profile.html.twig
        template: AppBundle:Profile:orders.html.twig
        routes:
            restaurant: restaurant
            order_invoice: profile_order_invoice
            order: profile_order
    methods:  [ GET ]

profile_restaurant_new:
    path: /profile/restaurants/new
    defaults:
        _controller: AppBundle:Profile:newRestaurant
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: profile_restaurant
            restaurants: profile_restaurants
            menu: profile_restaurant_menu
            dashboard: profile_restaurant_dashboard
            planning: profile_restaurant_planning
    methods: [ GET, POST ]

profile_restaurant:
    path: /profile/restaurants/{id}
    defaults:
        _controller: AppBundle:Profile:restaurant
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:form.html.twig
        routes:
            success: profile_restaurant
            restaurants: profile_restaurants
            menu: profile_restaurant_menu
            dashboard: profile_restaurant_dashboard
            planning: profile_restaurant_planning
    methods: [ GET, POST ]

profile_restaurants:
    path: /profile/restaurants
    defaults:
        _controller: AppBundle:Profile:restaurantList
        layout: AppBundle::profile.html.twig
        template: AppBundle:Profile:restaurants.html.twig
        routes:
            dashboard: profile_restaurant_dashboard
            menu: profile_restaurant_menu
            restaurant: profile_restaurant
    methods: [ GET ]

profile_restaurant_dashboard:
    path: /profile/restaurants/{restaurantId}/dashboard
    defaults:
        _controller: AppBundle:Profile:restaurantDashboard
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: profile_restaurants
            restaurant: profile_restaurant
            dashboard: profile_restaurant_dashboard
            dashboard_order: profile_restaurant_dashboard_order
            order_accept: profile_restaurant_dashboard_order_accept
            order_refuse: profile_restaurant_dashboard_order_refuse
            order_cancel: profile_restaurant_dashboard_order_cancel
            order_ready: profile_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

profile_restaurant_dashboard_order:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}
    defaults:
        _controller: AppBundle:Profile:restaurantDashboardOrder
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:dashboard.html.twig
        routes:
            restaurants: profile_restaurants
            restaurant: profile_restaurant
            dashboard: profile_restaurant_dashboard
            dashboard_order: profile_restaurant_dashboard_order
            order_accept: profile_restaurant_dashboard_order_accept
            order_refuse: profile_restaurant_dashboard_order_refuse
            order_cancel: profile_restaurant_dashboard_order_cancel
            order_ready: profile_restaurant_dashboard_order_ready
            user_details: user
    methods: [ GET ]

profile_restaurant_dashboard_order_accept:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}/accept
    defaults:
        _controller: AppBundle:Profile:acceptOrder
        redirect_route: profile_restaurant_dashboard_order
    methods: [ POST ]

profile_restaurant_dashboard_order_refuse:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}/refuse
    defaults:
        _controller: AppBundle:Profile:refuseOrder
        redirect_route: profile_restaurant_dashboard_order
    methods: [ POST ]

profile_restaurant_dashboard_order_ready:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}/ready
    defaults:
        _controller: AppBundle:Profile:readyOrder
        redirect_route: profile_restaurant_dashboard_order
    methods: [ POST ]

profile_restaurant_dashboard_order_cancel:
    path: /profile/restaurants/{restaurantId}/dashboard/{orderId}/cancel
    defaults:
        _controller: AppBundle:Profile:cancelOrderFromDashboard
        redirect_route: profile_restaurant_dashboard_order
    methods: [ POST ]

profile_restaurant_menu:
    path: /profile/restaurants/{id}/menu
    defaults:
        _controller: AppBundle:Profile:restaurantMenu
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:form-menu.html.twig
        routes:
            success: profile_restaurant_menu
            restaurants: profile_restaurants
            restaurant: profile_restaurant
            add_section: profile_restaurant_menu_add_section
    methods: [ GET ]

profile_restaurant_menu_add_section:
    path: /profile/restaurants/{id}/menu
    defaults:
        _controller: AppBundle:Profile:restaurantMenu
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:form-menu.html.twig
        routes:
            success: profile_restaurant_menu
            restaurants: profile_restaurants
            restaurant: profile_restaurant
            add_section: profile_restaurant_menu_add_section
        add_menu_section: true
    methods: [ POST ]

profile_restaurant_planning:
    path: /profile/restaurants/{id}/planning
    defaults:
        _controller: AppBundle:Profile:restaurantPlanning
        layout: AppBundle::profile.html.twig
        template: AppBundle:Restaurant:planning.html.twig
        routes:
            restaurants: profile_restaurants
            restaurant: profile_restaurant
    methods: [ GET, POST ]

profile_deliveries_calculate_price:
    path: /profile/deliveries/calculate-price
    defaults: { _controller: AppBundle:Profile:calculateDeliveryPrice }

profile_stores:
    path: /profile/stores
    defaults:
        _controller: AppBundle:Profile:storeList
        layout: AppBundle::profile.html.twig
        template: AppBundle:Profile:stores.html.twig
        routes:
            store: profile_store
            store_delivery: profile_store_delivery
    methods:  [ GET ]

profile_store:
    path: /profile/stores/{id}
    defaults:
        _controller: AppBundle:Profile:store
        layout: AppBundle::profile.html.twig
        routes:
            stores: profile_stores
            store_delivery: profile_store_delivery
    methods:  [ GET, POST ]

profile_store_delivery:
    path: /profile/stores/{id}/deliveries/new
    defaults:
        _controller: AppBundle:Profile:newStoreDelivery
        layout: AppBundle::profile.html.twig
        routes:
            stores: profile_stores
            store: profile_store
            success: profile_orders
            calculate_price: profile_deliveries_calculate_price
    methods:  [ GET, POST ]

profile_restaurant_order:
    path: /profile/restaurants/{id}/orders/new
    defaults:
        _controller: AppBundle:Profile:newRestaurantOrder
        layout: AppBundle::profile.html.twig
        template: AppBundle:Profile:newRestaurantOrder.html.twig
        # routes:
        #     stores: profile_stores
        #     store: profile_store
        #     success: profile_orders
        #     calculate_price: profile_deliveries_calculate_price
    methods:  [ GET, POST ]
